version: "3"
services:
  redis:
    container_name: certifier-redis
    image: redis:alpine
    ports:
      - "6379:6379"

  parity:
    container_name: certifier-parity
    image: parity/parity
    ports:
      - "8545:8545"
      - "127.0.0.1:8180:8180"
      - "8546:8546"
      - "30303:30303"
    volumes:
      # - "/home/me/.parity:/root/.local/share/io.parity.ethereum"
      - "/tmp/.parity:/root/.local/share/io.parity.ethereum"
    command: --chain ropsten --base-path /root/.local/share/io.parity.ethereum/  --jsonrpc-interface all --jsonrpc-hosts all --jsonrpc-apis all --ui-hosts=all --ui-interface all --ws-interface all --ui-no-validation

  frontend:
    container_name: certifier-frontend
    build: ./frontend
    command: npm start
    ports:
      - "8080:8080"

  backend:
    container_name: certifier-backend
    build: ./backend
    command: npm start
    ports:
      - "4000:4000"
